In [32]:
print(df.columns.tolist())

['shipment_id', 'supplier_id', 'product_id', 'shipment_date', 'expected_arrival', 'actual_arrival', 'shipment_quantity', 'shipment_status', 'product_name', 'category', 'unit_price', 'product_supplier_id', 'supplier_name', 'city', 'lead_time', 'rating', 'inventory_id', 'warehouse', 'stock_quantity', 'last_updated', 'disruption_id', 'disruption_type', 'severity', 'description', 'reported_date', 'decision_id', 'recommended_action', 'action_taken', 'decision_date', 'outcome_id', 'outcome_status', 'delay_days', 'cost_change', 'remarks']

In [31]:
clean_df = pd.read_csv("../data/clean_supply_chain.csv")

print(clean_df.shape)
clean_df.head()

(4033, 34)

,shipment_id,supplier_id,product_id,shipment_date,expected_arrival,actual_arrival,shipment_quantity,shipment_status,product_name,category,...,reported_date,decision_id,recommended_action,action_taken,decision_date,outcome_id,outcome_status,delay_days,cost_change,remarks
0,1,6,29,2025-06-03,2025-06-07,2025-06-12,16,In Transit,Architecto Product,Furniture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7,84,2025-06-16,2025-06-26,2025-06-24,106,Delayed,Ab Product,Clothing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,9,119,2026-03-17,2026-03-23,2026-03-24,325,In Transit,Maxime Product,Furniture,...,2026-05-10,45.0,Change Transport Route,Approved,2025-09-14,45.0,Failed,5.0,5007.42,Issue resolved successfully
3,4,5,140,2025-04-20,2025-04-23,2025-04-28,419,Cancelled,Recusandae Product,Groceries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,18,56,2025-11-20,2025-11-23,2025-11-28,136,Delayed,Error Product,Electronics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.to_csv("../data/clean_supply_chain.csv", index=False)

print("✅ clean_supply_chain.csv created successfully!")

✅ clean_supply_chain.csv created successfully!

In [23]:
print(df.shape)

df.head()

(4033, 34)

,shipment_id,supplier_id,product_id,shipment_date,expected_arrival,actual_arrival,shipment_quantity,shipment_status,product_name,category,...,reported_date,decision_id,recommended_action,action_taken,decision_date,outcome_id,outcome_status,delay_days,cost_change,remarks
0,1,6,29,2025-06-03,2025-06-07,2025-06-12,16,In Transit,Architecto Product,Furniture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7,84,2025-06-16,2025-06-26,2025-06-24,106,Delayed,Ab Product,Clothing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,9,119,2026-03-17,2026-03-23,2026-03-24,325,In Transit,Maxime Product,Furniture,...,2026-05-10,45.0,Change Transport Route,Approved,2025-09-14,45.0,Failed,5.0,5007.42,Issue resolved successfully
3,4,5,140,2025-04-20,2025-04-23,2025-04-28,419,Cancelled,Recusandae Product,Groceries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,18,56,2025-11-20,2025-11-23,2025-11-28,136,Delayed,Error Product,Electronics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
import pandas as pd

# Read datasets
suppliers = pd.read_csv("../data/suppliers.csv")
products = pd.read_csv("../data/products.csv")
inventory = pd.read_csv("../data/inventory.csv")
shipments = pd.read_csv("../data/shipments_cleaned.csv")
disruptions = pd.read_csv("../data/disruptions.csv")
decisions = pd.read_csv("../data/decisions.csv")
outcomes = pd.read_csv("../data/outcomes.csv")

# Rename columns
shipments = shipments.rename(columns={"quantity": "shipment_quantity"})
products = products.rename(columns={"supplier_id": "product_supplier_id"})

# Start with shipments
df = shipments.copy()

# Merge products
df = df.merge(products, on="product_id", how="left")

# Merge suppliers using shipment supplier_id
df = df.merge(suppliers, on="supplier_id", how="left")

# Merge inventory
df = df.merge(inventory, on="product_id", how="left")

# Merge disruptions
df = df.merge(disruptions, on="shipment_id", how="left")

# Merge decisions
df = df.merge(decisions, on="disruption_id", how="left")

# Merge outcomes
df = df.merge(outcomes, on="decision_id", how="left")

print(df.head())

   shipment_id  supplier_id  product_id shipment_date expected_arrival  \
0            1            6          29    2025-06-03       2025-06-07
1            2            7          84    2025-06-16       2025-06-26
2            3            9         119    2026-03-17       2026-03-23
3            4            5         140    2025-04-20       2025-04-23
4            5           18          56    2025-11-20       2025-11-23

  actual_arrival  shipment_quantity shipment_status        product_name  \
0     2025-06-12                 16      In Transit  Architecto Product
1     2025-06-24                106         Delayed          Ab Product
2     2026-03-24                325      In Transit      Maxime Product
3     2025-04-28                419       Cancelled  Recusandae Product
4     2025-11-28                136         Delayed       Error Product

      category  ...  reported_date  decision_id      recommended_action  \
0    Furniture  ...            NaN          NaN                     NaN
1     Clothing  ...            NaN          NaN                     NaN
2    Furniture  ...     2026-05-10         45.0  Change Transport Route
3    Groceries  ...            NaN          NaN                     NaN
4  Electronics  ...            NaN          NaN                     NaN

  action_taken  decision_date  outcome_id  outcome_status delay_days  \
0          NaN            NaN         NaN             NaN        NaN
1          NaN            NaN         NaN             NaN        NaN
2     Approved     2025-09-14        45.0          Failed        5.0
3          NaN            NaN         NaN             NaN        NaN
4          NaN            NaN         NaN             NaN        NaN

   cost_change                      remarks
0          NaN                          NaN
1          NaN                          NaN
2      5007.42  Issue resolved successfully
3          NaN                          NaN
4          NaN                          NaN

[5 rows x 34 columns]

In [20]:
df[["supplier_id", "supplier_name"]].head(10)

   supplier_id              supplier_name
0            6            Bhavsar-Sampath
1            6            Bhavsar-Sampath
2            6            Bhavsar-Sampath
3            6            Bhavsar-Sampath
4            7                   Wali PLC
5            7                   Wali PLC
6            9  Loyal, Varma and Tripathi
7            5              Chander-Sibal
8            5              Chander-Sibal
9            5              Chander-Sibal

In [25]:
df[["product_id", "product_name", "category"]].head(10)

   product_id        product_name     category
0          29  Architecto Product    Furniture
1          84          Ab Product     Clothing
2         119      Maxime Product    Furniture
3         140  Recusandae Product    Groceries
4          56       Error Product  Electronics
5          48       Neque Product      Medical
6         142     Dolorum Product    Groceries
7          19     Officia Product  Electronics
8         126        Nemo Product    Groceries
9         104  Laboriosam Product     Clothing

In [26]:
print(df.columns.tolist())

['shipment_id', 'supplier_id', 'product_id', 'shipment_date', 'expected_arrival', 'actual_arrival', 'shipment_quantity', 'shipment_status', 'product_name', 'category', 'unit_price', 'product_supplier_id', 'supplier_name', 'city', 'lead_time', 'rating', 'inventory_id', 'warehouse', 'stock_quantity', 'last_updated', 'disruption_id', 'disruption_type', 'severity', 'description', 'reported_date', 'decision_id', 'recommended_action', 'action_taken', 'decision_date', 'outcome_id', 'outcome_status', 'delay_days', 'cost_change', 'remarks']

In [17]:
missing_products = shipments[
    ~shipments["product_id"].isin(products["product_id"])
]

print("Missing product IDs:", missing_products["product_id"].unique())
print("Count:", len(missing_products))

Missing product IDs: []
Count: 0

In [27]:
print(products.head())

print(shipments.head())

print(products.dtypes)

print(shipments.dtypes)

   product_id         product_name   category  unit_price  product_supplier_id
0           1         Sint Product   Clothing     2204.33                   20
1           2       Veniam Product  Furniture      880.89                    5
2           3         Iure Product    Medical     1939.35                   19
3           4  Dignissimos Product   Clothing     2106.24                    6
4           5    Occaecati Product    Medical     1257.97                   15
   shipment_id  supplier_id  product_id shipment_date expected_arrival  \
0            1            6          29    2025-06-03       2025-06-07
1            2            7          84    2025-06-16       2025-06-26
2            3            9         119    2026-03-17       2026-03-23
3            4            5         140    2025-04-20       2025-04-23
4            5           18          56    2025-11-20       2025-11-23

  actual_arrival  shipment_quantity shipment_status
0     2025-06-12                 16      In Transit
1     2025-06-24                106         Delayed
2     2026-03-24                325      In Transit
3     2025-04-28                419       Cancelled
4     2025-11-28                136         Delayed
product_id               int64
product_name               str
category                   str
unit_price             float64
product_supplier_id      int64
dtype: object
shipment_id          int64
supplier_id          int64
product_id           int64
shipment_date          str
expected_arrival       str
actual_arrival         str
shipment_quantity    int64
shipment_status        str
dtype: object

In [28]:
clean_df = pd.read_csv("../data/clean_supply_chain.csv")

print(clean_df.shape)
clean_df.head()

(4033, 34)

,shipment_id,supplier_id,product_id,shipment_date,expected_arrival,actual_arrival,shipment_quantity,shipment_status,product_name,category,...,reported_date,decision_id,recommended_action,action_taken,decision_date,outcome_id,outcome_status,delay_days,cost_change,remarks
0,1,6,29,2025-06-03,2025-06-07,2025-06-12,16,In Transit,Architecto Product,Furniture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7,84,2025-06-16,2025-06-26,2025-06-24,106,Delayed,Ab Product,Clothing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,9,119,2026-03-17,2026-03-23,2026-03-24,325,In Transit,Maxime Product,Furniture,...,2026-05-10,45.0,Change Transport Route,Approved,2025-09-14,45.0,Failed,5.0,5007.42,Issue resolved successfully
3,4,5,140,2025-04-20,2025-04-23,2025-04-28,419,Cancelled,Recusandae Product,Groceries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,18,56,2025-11-20,2025-11-23,2025-11-28,136,Delayed,Error Product,Electronics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.to_csv("../data/clean_supply_chain.csv", index=False)

print("✅ clean_supply_chain.csv created successfully!")

✅ clean_supply_chain.csv created successfully!

In [29]:
df.isnull().sum()

shipment_id               0
supplier_id               0
product_id                0
shipment_date             0
expected_arrival          0
actual_arrival            0
shipment_quantity         0
shipment_status           0
product_name              0
category                  0
unit_price                0
product_supplier_id       0
supplier_name             0
city                      0
lead_time                 0
rating                    0
inventory_id              0
warehouse                 0
stock_quantity            0
last_updated              0
disruption_id          3433
disruption_type        3433
severity               3433
description            3433
reported_date          3433
decision_id            3433
recommended_action     3433
action_taken           3433
decision_date          3433
outcome_id             3433
outcome_status         3433
delay_days             3433
cost_change            3433
remarks                3433
dtype: int64

In [30]:
print(df.shape)
df.head()

(4033, 34)

,shipment_id,supplier_id,product_id,shipment_date,expected_arrival,actual_arrival,shipment_quantity,shipment_status,product_name,category,...,reported_date,decision_id,recommended_action,action_taken,decision_date,outcome_id,outcome_status,delay_days,cost_change,remarks
0,1,6,29,2025-06-03,2025-06-07,2025-06-12,16,In Transit,Architecto Product,Furniture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7,84,2025-06-16,2025-06-26,2025-06-24,106,Delayed,Ab Product,Clothing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,9,119,2026-03-17,2026-03-23,2026-03-24,325,In Transit,Maxime Product,Furniture,...,2026-05-10,45.0,Change Transport Route,Approved,2025-09-14,45.0,Failed,5.0,5007.42,Issue resolved successfully
3,4,5,140,2025-04-20,2025-04-23,2025-04-28,419,Cancelled,Recusandae Product,Groceries,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,18,56,2025-11-20,2025-11-23,2025-11-28,136,Delayed,Error Product,Electronics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
for name, data in {
    "suppliers": suppliers,
    "products": products,
    "inventory": inventory,
    "shipments": shipments,
    "orders": orders,
    "disruptions": disruptions,
    "decisions": decisions,
    "outcomes": outcomes,
}.items():
    print(f"\n{name.upper()}")
    print(data.columns.tolist())

SUPPLIERS
['supplier_id', 'supplier_name', 'city', 'lead_time', 'rating']

PRODUCTS
['product_id', 'product_name', 'category', 'unit_price', 'supplier_id']

INVENTORY
['inventory_id', 'product_id', 'warehouse', 'stock_quantity', 'last_updated']

SHIPMENTS
['shipment_id', 'supplier_id', 'product_id', 'shipment_date', 'expected_arrival', 'actual_arrival', 'quantity', 'shipment_status']

ORDERS
['order_id', 'supplier_id', 'product_id', 'order_date', 'quantity', 'expected_delivery', 'order_status']

DISRUPTIONS
['disruption_id', 'shipment_id', 'disruption_type', 'severity', 'description', 'reported_date']

DECISIONS
['decision_id', 'disruption_id', 'recommended_action', 'action_taken', 'decision_date']

OUTCOMES
['outcome_id', 'decision_id', 'outcome_status', 'delay_days', 'cost_change', 'remarks']

In [6]:
import pandas as pd

suppliers = pd.read_csv("../data/suppliers.csv")
products = pd.read_csv("../data/products.csv")
inventory = pd.read_csv("../data/inventory.csv")
shipments = pd.read_csv("../data/shipments_cleaned.csv")
orders = pd.read_csv("../data/orders.csv")
disruptions = pd.read_csv("../data/disruptions.csv")
decisions = pd.read_csv("../data/decisions.csv")
outcomes = pd.read_csv("../data/outcomes.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [1]:
import os
print(os.getcwd())
print(os.listdir("../data"))

c:\Users\Hp\OneDrive\Documents\GitHub\SupplyPrescript\notebooks
['decisions.csv', 'disruptions.csv', 'inventory.csv', 'orders.csv', 'outcomes.csv', 'products.csv', 'shipments.csv', 'shipments_cleaned.csv', 'suppliers.csv']

In [2]:
import os

print(os.listdir("../data"))

['decisions.csv', 'disruptions.csv', 'inventory.csv', 'orders.csv', 'outcomes.csv', 'products.csv', 'shipments.csv', 'shipments_cleaned.csv', 'suppliers.csv']

In [3]:
import os

print(os.getcwd())

c:\Users\Hp\OneDrive\Documents\GitHub\SupplyPrescript\notebooks

In [4]:
import pandas as pd

suppliers = pd.read_csv("../data/suppliers.csv")
print(suppliers.head())

   supplier_id                    supplier_name       city  lead_time  rating
0            1  Balasubramanian, Gara and Memon     Nadiad       5.69    4.88
1            2                         Gour Ltd   Bhilwara       8.05    3.83
2            3           Balan, Virk and Mangal  Bangalore       3.73    4.49
3            4              Rajagopal-Jayaraman      Jalna       1.00    3.51
4            5                    Chander-Sibal      Kochi       6.81    4.37

In [7]:
print("Suppliers:", suppliers.shape)
print("Products:", products.shape)
print("Inventory:", inventory.shape)
print("Shipments:", shipments.shape)
print("Orders:", orders.shape)
print("Disruptions:", disruptions.shape)
print("Decisions:", decisions.shape)
print("Outcomes:", outcomes.shape)

Suppliers: (20, 5)
Products: (150, 5)
Inventory: (150, 5)
Shipments: (4000, 8)
Orders: (5000, 7)
Disruptions: (600, 6)
Decisions: (600, 5)
Outcomes: (600, 6)